### ISSUE TITLE
View signup

### ISSUE THREAD

**Issue by keyurshah** [mediabeastnz/craft-commerce-back-in-stock#11]
Hello,

Is there a way to view a list of the signups and the products which have signups?

I don't see an admin panel in my installation.

Thanks.

**Comment by damienbuckley** [comment]
+1 for this. Failing something in admin, would it be possible to have the email sent to an admin too? Client wants to know which products people are waiting for.

**Comment by mylesthedev** [comment]
Great idea, I haven't had much time to work on this plugin recently but this would be a great addition in the next release.

**Comment by KingFrank1982** [comment]
Any idea when this is going to be implemented? I have several clients who would really like this.

**Comment by mylesthedev** [comment]
This is now implemented on the latest version `2.1.0`
