### ISSUE TITLE
Feature Request - Notify feedback

### ISSUE THREAD

**Issue by jlabs** [mediabeastnz/craft-commerce-back-in-stock#12]
Would it be possible to add in some form of feedback/trigger when someone requests to be notified? e.g. someone adds their email to notify, then when the page reloads they could see a custom message.

**Comment by mylesthedev** [comment]
I'd recommend using Ajax to submit the form when possible as you'll know if the submission was successful in the response.

However I understand not everyone will want to do it that way so I can return a flash message of some sort so when the page is redirected you can show a message.

**Comment by mylesthedev** [comment]
#17 fixes this
