### ISSUE TITLE
Prevent double subscriptions

### ISSUE THREAD

**Issue by arifje** [mediabeastnz/craft-commerce-back-in-stock#14]
Currently you can 'subscribe' the same email address multiple times and the notification is also sent the same amount of times. Should be check on existing email addresses combined with product variant id if you ask me?

**Comment by mylesthedev** [comment]
Thanks @skoften good spotting

**Comment by masiorama** [comment]
Hello, is this still planned? Thanks!

**Comment by mylesthedev** [comment]
Fixed with 1.4.1
