### ISSUE TITLE
Post Request Required

### ISSUE THREAD

**Issue by markcoogan** [mediabeastnz/craft-commerce-back-in-stock#15]
Hi there, 

We've installed the plugin and used the example form in the helper template, but when we submit the form we get the message:

Post request required

Is there any further steps required to get this working that we might have missed?

**Comment by TomDeSmet** [comment]
Add `method="post"` to your `form` element.

**Comment by markcoogan** [comment]
Hi Tom, 

Thanks for that. I had tried that before but it was doing the same thing, but seems to be refreshing the page now anyway. 

It doesn't appear to be sending a notification email though, is there anything you can think of that might be causing that?

**Comment by TomDeSmet** [comment]
That could be a number of things. Is your Craft mail correctly configured ? (Test it with the Craft test mail button).

Also, this may sound stupid but, this plugin is able to send 2 mails.
A notification for when you leave your e-mail to be notified. This you have to enable from the plugin settings.
A notification for when the product is back in stock, this only happens when the stock of the product is greater than 0 of course, so have you switched the stock while testing?

Sorry if I state the obvious, but sometimes issues have the simplest solution :)

**Comment by markcoogan** [comment]
Hi Tom, 

Thanks for your help.  I can confirm that the site can send emails and I've ticked the box to send a notification when the user enters their address to be notified.

I've just taken the helper form template and dropped that into the site as is, as its own template.  Does the form need to be integrated in all particular way?

**Comment by TomDeSmet** [comment]
Not realy, did you uncomment this in the code: `<input type="hidden" name="variantId" value="{# product.defaultVariant.id #}">`  ?

**Comment by markcoogan** [comment]
Hi Tom, 

That's right, I did.  I've got <input type="hidden" name="variantId" value="{ product.defaultVariant.id }">

That look ok?  Can I hard code that to a specific product for testing?

**Comment by TomDeSmet** [comment]
A specific variant ID of a product yes.

**Comment by markcoogan** [comment]
Hi Tom, 

I've done some more work on this and I have it at the point where it's successfully sending emails, thanks for your help.

The only small issue is that when someone requests to be notified, it does not send the confirmation straight away.  When the product is back in stock, and that email is sent, it then sends both emails at the same time.  

Is there anything I've missed that could be causing that?

**Comment by TomDeSmet** [comment]
Emails are added to the Craft CMS job queue. That queue is only executed when someone logs into the Control Panel or the queue command is run from the terminal.

So try this: subscribe to be notified, go to the CP and refresh (you should see an e-mail notification being sent in the queue), check your e-mail for the notification, update the stock, check your email for the second mail.

To make this work on a production server, you should add a CRON job to the server which periodically runs the Craft CMS queue.

**Comment by markcoogan** [comment]
Hi Tom, 

Thanks for that.  That all seems to be working correctly now.
