### ISSUE TITLE
Multi-site support in subject field

### ISSUE THREAD

**Issue by TomDeSmet** [mediabeastnz/craft-commerce-back-in-stock#16]
Hi,

It seems the subject field does not support translations?

I created a similar support issue for the abandoned cart plugin earlier: https://github.com/mediabeastnz/craft-commerce-abandoned-cart/issues/51

**Comment by mylesthedev** [comment]
Hi @TomDeSmet this was resolved in 1.4.2.

Note you'll have to create a `craft-commerce-back-in-stock.php` file in your translations folder and then override it like so:

```
return [
    "Order today, {{variant.title}} is now in stock" => "Order today, {{variant.title}} is available now!"
];
