### ISSUE TITLE
Add param for flash notice

### ISSUE THREAD

**Issue by TomDeSmet** [mediabeastnz/craft-commerce-back-in-stock#17]
Just like the Commerce `update-cart` controller:
`<input type="hidden" name="cartUpdatedNotice" :value="">`

I know we can also use `{% do craft.app.session.setFlash('stock', 'msg') %}` but that doesn't work when the `msg` is being added by Javascript. Because the Twig was already executed by then.

**Comment by mylesthedev** [comment]
This can be done using translations. Create a `translations/en/craft-commerce-back-in-stock.php` file for the required languages (you might have one or multiple.

And then override the following string: '{email} will be notified when {title} is available'

e.g.
```
return [
    '{email} will be notified when {title} is available' => 'You'll be notified when {title} becomes available'
]
```
