### ISSUE TITLE
Craft Commerce 3 Compatibility

### ISSUE THREAD

**Issue by daniellelecomte** [mediabeastnz/craft-commerce-back-in-stock#18]
Hello @mediabeastnz! Any plans to make this Commerce 3 ready? Thanks!

**Comment by mylesthedev** [comment]
Yes! Looking to update my plugins this month

**Comment by daniellelecomte** [comment]
Awesome - any updates here? Thanks!

**Comment by acantes** [comment]
Will updating the plugin also include an update to Craft Commerce 4? Asking for a keen client!

**Comment by mylesthedev** [comment]
Hi guys, I've just tested this using the latest Craft CMS 3 and Commerce 3 and everything works as expected.
I'll close this for now but if you have any specific issues please create a new issue.
