### ISSUE TITLE
Register interest throws an error

### ISSUE THREAD

**Issue by joene789** [mediabeastnz/craft-commerce-back-in-stock#30]
### Describe the bug

TypeError: Cannot assign string to property verbb\backinstock\models\Log::$options of type array

![image](https://github.com/user-attachments/assets/9c13dccf-f266-4337-b5ea-d96c19d6dd45)

I guess in BaseController the options param should be json decoded?

![image](https://github.com/user-attachments/assets/e131f8d1-a4f1-4731-857a-8d02a2cf72e1)

### Steps to reproduce

Register an email in the frontend form

### Craft CMS version

4.12.9

### Plugin version

3.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.1](https://github.com/verbb/back-in-stock/releases/tag/3.0.1)
