### ISSUE TITLE
PostgreSQL error on 3.0.2

### ISSUE THREAD

**Issue by boboldehampsink** [mediabeastnz/craft-commerce-back-in-stock#32]
### Describe the bug

```
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column logs.variantid does not exist
LINE 3: LEFT JOIN "commerce_variants" "variants" ON logs.variantId =...
                                                    ^
HINT:  Perhaps you meant to reference the column "logs.variantId".
  File "/index.php", line 28
    $app->run();
```

It looks like you forgot that Postgres is case-sensitive ;-)

### Steps to reproduce

1. Try to load the CP overview in Postgres

### Craft CMS version

4

### Plugin version

3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Ooo, good call on that - I forgot to wrap those join conditions correctly. Fixed in [3.0.3](https://github.com/verbb/back-in-stock/releases/tag/3.0.3)
