### ISSUE TITLE
Translations variables bug

### ISSUE THREAD

**Issue by pieterjandebruyne** [mediabeastnz/craft-commerce-back-in-stock#5]
Hi,

Please fix line 142 in BaseController.php
Your translation string includes variables and can't be translated as a result.

Please change to:
`'message' => Craft::t('craft-commerce-back-in-stock', '{email} will be notified when {title} is available', ['email' => $email, 'title' => $variant->title]),`

This way we can use  '{email} will be notified when {title} is available' in our translation files.

Thanks.

**Comment by mylesthedev** [comment]
On it!

**Comment by mylesthedev** [comment]
@pieter-janDB fixed in 1.3.1
